app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'app'

urlpatterns = [
    path('',views.index,name='home'),
    path('about/',views.about,name='about'),
    path('contact/', views.contact, name='contact'),
    path('product/',views.product, name='product'),
    path('login/',views.user_login, name='account'),
    path('logout/',views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('reviews/',views.all_review, name='reviews'),
    path('cart/',views.cart,name='cart'),
    path('checkout/',views.checkout,name='checkout'),
    path('career/',views.career,name='career'),
    path('payment/<int:key>/', login_required(views.PaymentView.as_view()), name='payment'),
]

uv/urls.py
from django.contrib import admin
from django.urls import path,include

app_name = 'uv'

urlpatterns = [
    path('sankalp/', admin.site.urls, name = 'admin'),
    path('',include('app.urls',namespace='app')),
]

handler404 = 'app.views.handler404'
handler500 = 'app.views.handler500'

app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django_countries.fields import CountryField

User = get_user_model()

# Create your models here.
class Contact(models.Model):
    author = models.CharField(max_length=1000)
    email = models.EmailField()
    phone = models.CharField(max_length=12,blank=True)
    subject = models.CharField(max_length=1000)
    message = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-time']

    def __str__(self):
        return "Contact - {} - {}".format(self.author,self.email)


class Review(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    rating = models.SmallIntegerField(default=5,blank=True)
    comment = models.TextField()
    author = models.CharField(max_length=1000)
    email = models.EmailField()
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return "{} - {}".format(self.author,self.email)


class Product(models.Model):
    name = models.CharField(max_length=1000, default='UV PURE',unique=True)
    price = models.FloatField(default=4399)

    def __str__(self):
        return "{} - {}".format(self.name, self.price)

    def get_actions(self, request):
        actions = super().get_actions(request)
        if 'delete_selected' in actions:
            del actions['delete_selected']
        return actions


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    count = models.IntegerField(default=1)
    time = models.DateTimeField(auto_now_add=True)

    def get_price(self):
        return self.item.price

    def get_total(self):
        return (self.item.price)*(self.count)

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return self.user.username


class Checkout(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete = models.SET_NULL, blank=True, null=True )
    ordered = models.BooleanField(default=False)
    country = CountryField(default="IN",multiple=False)
    name = models.CharField(max_length=1000)
    username = models.CharField(max_length=1000)
    email = models.EmailField(max_length=1000)
    address = models.TextField()
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    zip_code = models.IntegerField()
    phone = models.CharField(max_length=12)
    notes = models.TextField(blank=True,null=True)
    time = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ['-time']


class Career(models.Model):
    name = models.CharField(max_length=1000) 
    father_name = models.CharField(max_length=1000)
    dob = models.DateField()
    phone = models.CharField(max_length=10)
    email = models.EmailField()
    address = models.TextField()
    profession_role = models.CharField(max_length=1000)
    experience = models.CharField(max_length=1000)
    message = models.TextField()
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return self.name


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete = models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} - {}".format(self.user.username, self.stripe_charge_id)

    class Meta:
        ordering = ['-time']

templates/account.html
{% extends 'base.html' %}{% load static %}
{% block title %}{{title}}{% endblock  %}
{% block  content %}

	<!-- =====================================
    	==== Start breadcrumb -->
   	<div class="breadcrumb">
   		<!-- container -->
		<div class="container">
			<h1>Account</h1>
			<ol class="item-breadcrumb">
	            <li><a href="{% url 'app:home' %}">Home</a></li>
	            <li>account</li>     
            </ol>
		</div>
		<!-- /container -->
   	</div>
    <!-- =====================================
    	==== End breadcrumb -->


	<!-- =====================================
    	==== Start account -->
	<div class="page-account">
		<!-- container -->
		<div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="account-wrapper">
                    	<ul class="account-tab-list nav">
                        	<li class="active"><a data-toggle="tab" href="#login">login</a></li>
						    <li><a data-toggle="tab" href="#register">register</a></li>
                        </ul>
						<center><p style="color:red;"><span>{{warning}}</span></p></center>
                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endif %}

                        <div class="tab-content">
                            <div id="login" class="tab-pane fade in active">
                                <div class="account-form-container login-form">
                                    <div class="account-form">
                                        <form action="{% url 'app:account' %}" method="POST">{% csrf_token %}
                                            <input type="text" name="username" placeholder="Username">
                                            <input type="password" name="password" placeholder="Password">
                                            <div class="button-box">
                                                <div class="login-toggle-btn d-flex justify-content-between">
                                                	<div class="remember d-flex">
                                                		 <input type="checkbox">
                                                    	<label>Remember me</label>
                                                	</div>
                                                   	<div class="forgot">
                                                    	<a href="#">Forgot Password?</a>

                                                    </div>
                                                </div>
                                                <button type="submit" class="btn btn-default btn-normal"><span>Login</span></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div id="register" class="tab-pane fade">
                                <div class="account-form-container register-form">
                                    <div class="account-form">
                                        <form action="{% url 'app:register' %}" method="POST">{% csrf_token %}
											<input type="text" name="username" maxlength="150" required="" id="id_username" placeholder="User Name (UNIQUE)">
											<input type="text" name="first_name" maxlength="30" id="id_first_name" placeholder="Full Name">
											<input type="email" name="email" maxlength="254" id="id_email" placeholder="Email">
											<input type="password" name="password" required="" id="id_password" placeholder="Password">
                                            <div class="button-box">
                                                <button type="submit" class="btn btn-default btn-normal"><span>Register</span></button>
                                            </div>
                                        </form> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
		<!-- /container -->
	</div>
	<!-- =====================================
    	==== End account -->
{% endblock %}

templates/base.html
{% include "header.html" %}

{% block content %}

{% endblock %}

{% include "footer.html" %}

templates/cart.html
{% extends 'base.html' %}{% load static %}
{% block title %}{{title}}{% endblock  %}
{% block  content %}
	<!-- =====================================
    	==== Start breadcrumb -->
   	<div class="breadcrumb">
   		<!-- container -->
		<div class="container">
			<h1>Cart</h1>
			<ol class="item-breadcrumb">
	            <li><a href="{% url 'app:home' %}">Home</a></li>
	            <li>Cart</li>     
            </ol>
		</div>
		<!-- /container -->
   	</div>
    <!-- =====================================
    	==== End breadcrumb -->


	<!-- =====================================
    	==== Start cart -->
	<div class="page-cart">
		<!-- container -->
		<div class="container">
			<div class="row">
				<div class="col-md-8">
					<form class="cart-form table_responsive" action="{% url 'app:cart' %}" method="POST">{% csrf_token %}
						<table class="shop_table table cart cart-form__contents">
							<thead>
								<tr>
									<th class="product-thumbnail">Product</th>
									<th class="product-name">Name</th>
									<th class="product-price">Price</th>
									<th class="product-quantity">Quantity</th>
									<th class="product-subtotal">Total</th>
								</tr>
							</thead>
							<tbody>
								<tr class="cart-form__cart-item cart_item">
									<td class="product-thumbnail">
										<a href="{% url 'app:product' %}">
											<img src="{% static 'assets/images/product/product_2.jpg' %}" alt="">
										</a>
									</td>
									<td class="product-name" data-title="Product">
										<a href="{% url 'app:product' %}">{{cart.item.name}}</a>	
									</td>
									<td class="product-price" data-title="Price">
										<span class="price-amount amount"><span class="price-currencySymbol">₹</span>{{cart.item.price}}</span>			
									</td>
									<td class="product-quantity" data-title="Quantity">
										<div class="quantity">
											<input type="number" class="input-text qty text" name="count" step="1" min="1" value="{{cart.count}}" title="Qty" size="4">
										</div>
									</td>
									<td class="product-subtotal" data-title="Total">
										<span class="price-amount amount"><span class="price-currencySymbol">₹</span>{{total}}</span>					
									</td>

								</tr>

								<tr>
									<td colspan="6" class="actions">
										<div class="clearfix">
										<div class="coupon pull-left"> 
											<input type="text" name="coupon_code" class="input-text " id="coupon_code" value="" placeholder="No Coupons" readonly> 
										</div>
											<div class="pull-right"> 
												<input type="submit" class="btn btn-primary" name="update_cart" value="Update Cart"> 
											</div>
										</div>
									</td>
								</tr>
							</tbody>
						</table>
					</form>
				</div>
				<div class="col-md-4">
					<div class="grand-totall">
                        <div class="title-wrap">
                            <h4 class="cart-bottom-title section-bg-gary-cart">Cart Total</h4>
                        </div>
                        <h5>Total products: <span>₹{{total}}</span></h5>
                        <div class="total-shipping">
                            <h5>Total shipping</h5>
                            <ul>
                                <li><input type="checkbox"> Standard: <span>₹0.00</span></li>
                                <li><input type="checkbox"> Express: <span>₹0.00</span></li>
                            </ul>
                        </div>
                        <h4 class="grand-totall-title">Total:  <span>₹{{total}}</span></h4>
                        <a href="{% url 'app:checkout' %}" class="btn btn-primary checkout-button">Proceed to Checkout</a>
                    </div>
				</div>
			</div>
		</div>
		<!-- /container -->
	</div>
	<!-- =====================================
    	==== End cart -->

{% endblock %}

templates/footer.html
{% load static %}
    <footer class="site-footer site-footer-3 clearfix">
    	<div class="site-footer__main section-bg" style="background-image:url({% static 'assets/images/bg_footer.jpg)' %}">
	    	<div class="container">
	    		<div class="col-md-5 col-sm-6 col-xs-12 footer-block pb-30">
		    		 <img src="{% static 'assets/images/CodeSankalp.png' %}" alt="" style="height: 30px;"> 
		    		 <p class="address pt-30">Office: UV Pure Private Limited C-52 Sector-6 Near Noida Authority, Noida-201301 (Uttar Pradesh)<br/>
						Phone: (+91) 8700766696<br/>
						Email: <span>sankalp123427@gmail.com / codesankalp@gmail.com</span>
					</p>
					<ul class="social pt-10">
						<li>
							<a href="#"><i class="fa fa-facebook"></i></a>
						</li>
						<li>
							<a href="https://twitter.com/codesankalp" target="_blank"><i class="fa fa-twitter"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-google"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-instagram"></i></a>
						</li>
						<li>
							<a href="#"><i class="fa fa-pinterest"></i></a>
						</li>
					</ul>
		    	</div>
		    	<div class="col-md-4 col-sm-6 col-xs-12 footer-block pb-30">
	    			<center><h3 class="widget-title">Quick Links</h3>
	    			<ul>
	    				<li><a href="{% url 'app:about' %}">About Us</a></li>
	    				<li><a href="{% url 'app:contact' %}">Contact Us</a></li>
	    				<li><a href="{% url 'app:product' %}">Our Product</a></li>
	    				<li><a href="{% url 'app:career' %}">Career</a></li>
	    				<li><a href="{% url 'app:home' %}">Home</a></li>
	    			</ul></center>
		    	</div>

		    	{% comment %} <div class="col-md-2 col-sm-6 col-xs-12 footer-block pb-30">
	    			<img src="{% static 'assets/images/lamp2.png' %}">
		    	</div> {% endcomment %}
		    	<div class="col-md-3 col-sm-6 col-xs-12 footer-block pb-30">
		    		<h3 class="widget-title">CONNECT WITH US</h3>
		    		<div class="features skin1">
		    			<div class="features_list">
							<div class="features-images">
								<img src="{% static 'assets/images/icon_mail.png' %}" alt="">
							</div>
							<div class="features-description">
								<h4>Do you have any question?</h4>
								<p>
									sankalp123427@gmail.com
								</p>
								<p>
									codesankalp@gmail.com
								</p>
							</div>
						</div>
						<div class="features_list">
							<div class="features-images">
								<img src="{% static 'assets/images/icon_phone.png' %}" alt="">
							</div>
							<div class="features-description">
								<h4>(+91) 8700766696</h4>
								<p>
									(+91) 8700766696
								</p>
							</div>
						</div>
		    		</div>
		    		<div class="payment pt-20">
		        		<img src="{% static 'assets/images/payment.png' %}" alt="">
		        	</div>
		    	</div>
		    </div>
	   </div>
	  <div class="site-footer__copyright">
	   		<div class="container">
	    		<div class="copyright pull-left">
	        		© 2020. All rights reserved.<a href="{% url 'app:home' %}" target="_blank">UV Pure Pvt. Ltd.</a>
	        	</div>
				<div class="copyright pull-right">
	        		© Developed By <a href="https://www.linkedin.com/in/codesankalp/" target="_blank">Sankalp</a>
	        	</div>
	       </div>
	   </div>
    </footer>
    <!-- =====================================
    	==== End footer -->

   	<!-- back-to-top-->
    <div id="back-to-top"></div>
    <!-- back-to-top -->
     

    <!-- =====================================
    	====Start preloader -->
    <div id="preloader">
		<div class="preloader">
			<span></span>
			<span></span>
			<span></span>
			<span></span>
		</div>
	</div>
    <!-- =====================================
    	==== End preloader -->

 	<!-- =====================================
    	====Start all js here -->

	<!-- jquery js-->
   	<script src="{% static 'assets/js/jquery.min.js' %}"></script>

	<!-- bootstrap js-->
	<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

	<!-- slick js-->
	<script src="{% static 'assets/js/slick.min.js' %}"></script>

	<!-- spritespin js-->
	<script src="{% static 'assets/js/jquery-ui.min.js' %}"></script>

	<!-- sliderPro js-->
	<script src="{% static 'assets/js/jquery.sliderPro.min.js' %}"></script>

    <!-- waypoints js-->
    <script src="{% static 'assets/js/jquery.waypoints.js' %}"></script>

	<!-- counterup js-->
	<script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>

	<!-- custom js-->
	<script src="{% static 'assets/js/custom.js' %}"></script>

	<script src="{% static 'assets/js/pay.js' %}"></script>
    
	<!-- =====================================
    	==== End all js herej -->
     
</body>
</html>

templates/header.html
<!DOCTYPE html>{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
    <meta name="robots" content="noindex, follow" />

	<title>{% block title %}{{title}}{% endblock %}</title>

	<!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/favicon.png' %}">

	<!-- font-awesome CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}">

	<!-- preloader CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/preloader.css' %}"> 

	<!-- slider-pro CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/slider-pro.css' %}">

	<!-- slick CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/slick.css' %}">

	<!-- main CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">

	<!-- google font CSS -->
	<link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

	<!-- payment css -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/pay.css' %}">
</head>

<body>
	<!-- =====================================
    	==== Start header -->
	<!-- header-desktop -->
	<header class="header">
		<div class="topbar pt-30 pb-30">
			<div class="container d-flex justify-content-between align-items-center">
				<div class="top-bar">
					<div class="header-language item-dropdown header-currency item-dropdown">
						<a class="logo" href="{% url 'app:home' %}">
							<img src="{% static 'assets/images/CodeSankalp.png' %}" alt="" style="height: 27px;"> 
						</a>
					</div>
				</div>
				<div class="otf-flex-item" >
					</div>
				<div class="navbar-header" style="text-align: center;">
					<h4>Developed By <a href="https://linkedin.com/in/codesankalp/" target="_blank">Sankalp</a></h4>
					<p>Features - admin interface, payment integration, checkout, etc... <br>
						This site can be customized for other products in minutes by admin.</p>
				
				</div>
				<div class="otf-flex-item"></div>
				<div>
					<span class="text-quote-author" style=" font-size: 20px; color: #0523AD; font-family: Rokkitt,Georgia,serif;"><b>UV PURE PRIVATE LIMITED </b></span><br>
					<span class="text-quote-quote" style="font-size: 15px;"><b>“अब बंद करें केमिकल, सैिनटाइज़र व साबुन</b></span><br>
                    <span class="text-quote-quote" style=" font-size: 15px;"><b>की धुलाई किरए सूरज सी रौशनी से सफाई |”</b></span>
				</div>
		    </div>
		</div>
	    <!-- header-main -->
	    <div class="header-main pb-10 pt-10">
	    	<div class="container">
			    <nav id="nav" class="navbar">
					<!--  Main navigation  -->
					<ul class="main-nav nav navbar-nav navbar-right">
						<li class="dropdown active">
							<a href="{% url 'app:home' %}">Home</a>
						</li>
			         	<li class="dropdown">
			         		<a href="{% url 'app:product' %}">Buy Product</a>
			         	</li>
			           	<li class="dropdown"><a href="{% url 'app:about' %}">About</a></li>
			            <li class="dropdown">
			            	<a href="{% url 'app:career' %}">Career</a>
			            </li>
			            <li><a href="{% url 'app:contact' %}">Contact</a></li>
						<li>
							{% if not user.is_authenticated %}
							<a href="{% url 'app:account' %}" class="account-btn">
								<img src="{% static 'assets/images/icon_account.png' %}" alt="">
								Login
							</a>
						
							{% endif %}{% if user.is_authenticated %}
							<a href="{% url 'app:logout' %}" class="account-btn">
								<i class="fa fa-sign-out" aria-hidden="true"></i>
								Logout
							</a>
							{% endif %}
						</li>
						

				    <!-- cart -->
						<li>
							<a href="{% url 'app:cart' %}" class="site-header__cart-toggle">
								<span class="cartcount">1</span>
								<i class="fa fa-shopping-basket" aria-hidden="true"></i> 
								<span class="cartcost"><span class="money" data-currency-usd="₹CART">CART (₹)</span></span>
							</a>
						</li>
						<li>
						{% if user.is_superuser %}
						<a class="site-header__cart-toggle" href="{% url 'admin:index' %}">Admin<i class="fa fa-long-arrow-right" aria-hidden="true"></i> </a>
						{% endif %}
						</li>
		        </div>
					</ul>
					<!-- /Main navigation -->
				</nav>
	    	</div>
	    </div>
	    <!-- /header-main -->
	</header>
	<!-- /header-desktop -->
	<!-- header-mobile -->
	<div class="header-mobile">
		<nav class="navbar">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <!-- logo -->
		      <a class="logo" href="{% url 'app:home' %}">
					<img src="{% static 'assets/images/CodeSankalp.png' %}" alt="" style="height:26px;"> 
				</a>
		      <!-- logo -->
		    </div>

		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      	<ul class="nav navbar-nav">
			       <li>
			          	<a href="{% url 'app:home' %}" >Home</a>
		       		</li>
			        <li>
			          	<a href="{% url 'app:product' %}" >Buy Product</a>
		       		</li>
		       		<li>
			          	<a href="{% url 'app:career' %}" >Career</a>
		       		</li>
		       		<li><a href="{% url 'app:contact' %}">Contact</a></li>
		      	</ul>
		    </div>
		</nav>
	</div>
	<div class="footer-mobile-bar">
		<ul class="columns-2">
			<li class="my-account">
							{% if not user.is_authenticated %}
							<a href="{% url 'app:account' %}" class="my-accrount-footer">
								<i class="fa fa-user-o" aria-hidden="true"></i>
							</a>
						
							{% endif %}{% if user.is_authenticated %}
							<a href="{% url 'app:logout' %}" class=class="my-accrount-footer">
								<i class="fa fa-sign-out" aria-hidden="true"></i>
							</a>
							{% endif %}          
			</li>
			<li class="cart">
				<a class="footer-cart-contents" href="{% url 'app:cart' %}" title="View your shopping cart">
					<i class="fa fa-shopping-basket" aria-hidden="true"></i>
					<span class="count">1</span>
				</a>
			</li>
		</ul>
    </div>
	<!-- End header ====
    	======================================= -->

	

templates/payment.html
{% extends 'base.html' %}{% load static %}
{% block title %}{{title}}{% endblock  %}
{% block  content %}

	  <!-- =====================================
      ==== Start breadcrumb -->
   	<div class="breadcrumb">
   		<!-- container -->
		<div class="container">
			<h1>Cart</h1>
			<ol class="item-breadcrumb">
	            <li><a href="{% url 'app:home' %}">Home</a></li>
	            <li>Payment</li>     
            </ol>
		</div>
		<!-- /container -->
   	</div>
   <!-- =====================================
      ==== End breadcrumb -->


	<!-- =====================================
      ==== Start checkout-form-->
  <i class="{{ form.country.flag_css }}"></i>
	<div class="checkout-form">
		<!-- container -->
		<div class="container">
			<!-- Row -->
            <div class="row">
                <div class="col-lg-12 col-md-12">

                    <div class="order-wrapper">
                        <h3>Your order</h3>
                        <div class="order-table table-responsive mb-30">
                            <table>
                                <thead>
                                    <tr>
                                        <th class="product-name">Product</th>
                                        <th class="product-total">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="product-name"> {{cart.item.name}} <strong> × {{cart.count}}</strong></td>
                                        <td class="amount"> ₹{{total}}</td>
                                    </tr>
                                    
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>Cart Subtotal</th>
                                        <td>₹{{total}}</td>
                                    </tr>
                                    <tr>
                                        <th>Order Total</th>
                                        <td><strong>₹{{total}}</strong></td>
                                    </tr>
                                </tfoot>
                            </table>    
                        </div>
                        <div class="payment-method">
                          <div class="panel-default">
                                <a class="righ_10" data-toggle="collapse" data-target="#collapsethree" aria-controls="collapseOne">Payment Method</a>

                                <div id="collapsethree" class="" data-parent="#accordion">
                                    <div class="card-body2">
                                    <script src="https://js.stripe.com/v3/"></script>

                                            <form action="{% url 'app:payment' key %}" method="post" id="payment-form">{% csrf_token %}
                                            <div class="form-row">
                                                <label for="card-element">
                                                Credit or debit card
                                                </label>
                                                <div id="card-element">
                                                <!-- A Stripe Element will be inserted here. -->
                                                </div>

                                                <!-- Used to display form errors. -->
                                                <div id="card-errors" role="alert"></div>
                                            </div>
                                            <div class="order-button">
                                                <center><button type="submit" class="btn-primary">Submit Payment</button></center> 
                                            </div>
                                            </form>
                                    </div>
                                </div>
                            </div> 

                                 
                        </div>
                        </form>    
                    </div>  
                </div>
            </div> 
            <!-- Row -->
        </div>
		<!-- /container -->
	</div>
	<!-- =====================================
      ==== End checkout-form -->

{% endblock %}